# Generated by Django 5.0.4 on 2024-05-09 20:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('sezione', models.CharField(default='', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]*$', 'Only CAPS characters are allowed.')])),
            ],
            options={
                'verbose_name_plural': 'Classe',
            },
        ),
        migrations.CreateModel(
            name='Gita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stato', models.CharField(choices=[('IN_PROGRAMMA', 'In programma'), ('IN_CORSO', 'In corso'), ('TERMINATA', 'Terminata')], default='IN_PROGRAMMA', max_length=20)),
                ('Data_ritrovo', models.DateTimeField(blank=True, null=True)),
                ('Data_rientro', models.DateTimeField(blank=True, null=True)),
                ('Luogo_ritrovo', models.CharField(max_length=20)),
                ('Luogo_rientro', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Gita',
            },
        ),
        migrations.CreateModel(
            name='Documenti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titolo', models.CharField(max_length=20)),
                ('Descrizione', models.CharField(default='', max_length=300)),
                ('Allegato', models.FileField(default='', upload_to='documenti/')),
                ('groups', models.ManyToManyField(related_name='documenti', to='auth.group')),
                ('Gita', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gite.gita')),
            ],
            options={
                'verbose_name_plural': 'Documenti',
            },
        ),
        migrations.CreateModel(
            name='Docenti_gita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Gita', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gite.gita')),
            ],
            options={
                'verbose_name_plural': 'Docenti_gita',
            },
        ),
        migrations.CreateModel(
            name='Classe_gita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classe', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gite.classe')),
                ('Gita', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gite.gita')),
            ],
            options={
                'verbose_name_plural': 'Classe_gita',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Presenti_prenotati',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gita', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gite.gita')),
                ('utente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Presenti_prenotati',
            },
        ),
        migrations.CreateModel(
            name='Proposta_Gita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titolo', models.CharField(max_length=20)),
                ('Descrizione', models.CharField(max_length=300)),
                ('Data', models.DateTimeField(blank=True, null=True)),
                ('Posto', models.CharField(max_length=20)),
                ('Costo', models.FloatField()),
                ('Stato', models.CharField(choices=[('IN_ELABORAZIONE', 'In elaborazione'), ('CONFERMATA', 'Confermata'), ('RIFIUTATA', 'Rifiutata')], default='IN_ELABORAZIONE', max_length=20)),
                ('Creatore', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Proposte_Gita',
            },
        ),
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titolo', models.CharField(max_length=20)),
                ('Descrizione', models.CharField(default='', max_length=300)),
                ('Classe', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gite.classe')),
                ('Documenti', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gite.documenti')),
                ('Gita', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gite.gita')),
                ('groups', models.ManyToManyField(related_name='notifica', to='auth.group')),
                ('Proposta_Gita', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gite.proposta_gita')),
            ],
            options={
                'verbose_name_plural': 'Notifica',
            },
        ),
        migrations.AddField(
            model_name='gita',
            name='Proposta_Gita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gite.proposta_gita'),
        ),
        migrations.CreateModel(
            name='Attività',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titolo', models.CharField(max_length=20)),
                ('Descrizione', models.CharField(max_length=300)),
                ('Costo', models.FloatField()),
                ('Stato', models.CharField(choices=[('IN_ELABORAZIONE', 'In elaborazione'), ('CONFERMATA', 'Confermata'), ('RIFIUTATA', 'Rifiutata')], default='IN_ELABORAZIONE', max_length=20)),
                ('Proposta_Gita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gite.proposta_gita')),
            ],
            options={
                'verbose_name_plural': 'Attività',
            },
        ),
    ]
