# Generated by Django 5.0.4 on 2024-05-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gite', '0002_alter_proposta_gita_creatore'),
    ]

    operations = [
        migrations.AddField(
            model_name='gita',
            name='classi',
            field=models.ManyToManyField(related_name='gite', to='gite.classe'),
        ),
    ]
