# Generated by Django 5.0.4 on 2024-05-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gite', '0003_gita_classi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gita',
            name='classi',
        ),
    ]
