# Generated by Django 5.0.4 on 2024-05-16 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gite', '0004_remove_gita_classi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attività',
            name='Costo',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='proposta_gita',
            name='Costo',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
