# Generated by Django 5.0.3 on 2024-05-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gite', '0005_alter_attività_costo_alter_proposta_gita_costo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
