# Generated by Django 5.0.4 on 2024-05-17 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gite', '0006_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='gita',
            name='Allegato',
            field=models.FileField(blank=True, null=True, upload_to='documenti/'),
        ),
        migrations.AlterField(
            model_name='attività',
            name='Costo',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='proposta_gita',
            name='Costo',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30000)]),
        ),
    ]
