# Generated by Django 5.0.4 on 2024-05-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gite', '0009_alter_user_classe_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifica',
            name='Classe',
        ),
        migrations.AddField(
            model_name='notifica',
            name='Classe',
            field=models.ManyToManyField(related_name='notifica', to='gite.classe'),
        ),
    ]
