# Generated by Django 5.0.4 on 2024-05-20 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gite', '0010_remove_notifica_classe_notifica_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifica',
            name='Documenti',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='gite.documenti'),
        ),
    ]
