# Generated by Django 5.0.4 on 2024-05-20 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gite', '0011_alter_notifica_documenti'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'verbose_name_plural': 'Classi'},
        ),
        migrations.AddField(
            model_name='notifica',
            name='utenti_letto',
            field=models.ManyToManyField(blank=True, related_name='notifiche_lette', to=settings.AUTH_USER_MODEL),
        ),
    ]
