# Generated by Django 5.0.4 on 2024-05-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_caratteristiche_profile_cognome_profile_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='caratteristiche',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
