# Generated by Django 5.0.4 on 2024-05-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_caratteristiche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='caratteristiche',
            field=models.CharField(blank=True, choices=[('dsa', 'DSA'), ('disabile', 'Disabile'), ('allergico', 'Allergico')], max_length=100, null=True),
        ),
    ]
