# Generated by Django 5.0.4 on 2024-05-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_caratteristiche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cognome',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nome',
        ),
        migrations.AlterField(
            model_name='profile',
            name='caratteristiche',
            field=models.CharField(blank=True, choices=[('nessuna', 'Nessuna'), ('dsa', 'DSA'), ('disabile', 'Disabile'), ('allergico', 'Allergico')], max_length=100, null=True),
        ),
    ]
