# Generated by Django 5.0.3 on 2024-05-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_tipi_allergie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tipi_allergie',
            new_name='specifiche',
        ),
    ]
