# Generated by Django 5.0.3 on 2024-05-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_tipi_allergie_profile_specifiche'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='specifiche',
            new_name='dettagli',
        ),
    ]
