# Generated by Django 5.0.4 on 2024-05-03 12:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('sezione', models.CharField(default='', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Classe',
            },
        ),
        migrations.CreateModel(
            name='Gita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titolo', models.CharField(max_length=20)),
                ('Costo', models.FloatField()),
                ('Stato', models.CharField(choices=[('IN_PROGRAMMA', 'In programma'), ('IN_CORSO', 'In corso'), ('TERMINATA', 'Terminata')], default='IN_PROGRAMMA', max_length=20)),
                ('Data_ritrovo', models.DateTimeField(blank=True, null=True)),
                ('Data_rientro', models.DateTimeField(blank=True, null=True)),
                ('Luogo_ritrovo', models.CharField(max_length=20)),
                ('Luogo_rientro', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Gita',
            },
        ),
        migrations.CreateModel(
            name='Proposta_Gita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titolo', models.CharField(max_length=20)),
                ('Descrizione', models.CharField(max_length=300)),
                ('Data', models.DateTimeField(blank=True, null=True)),
                ('Posto', models.CharField(max_length=20)),
                ('Costo', models.FloatField()),
                ('Stato', models.CharField(choices=[('IN_ELABORAZIONE', 'In elaborazione'), ('CONFERMATA', 'Confermata'), ('RIFIUTATA', 'Rifiutata')], default='IN_ELABORAZIONE', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Proposte_Gita',
            },
        ),
        migrations.CreateModel(
            name='Documenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titolo', models.CharField(max_length=20)),
                ('Descrizione', models.CharField(default='', max_length=300)),
                ('Allegato', models.FileField(default='', upload_to='documenti/')),
                ('Gita', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.gita')),
            ],
            options={
                'verbose_name_plural': 'Documenti',
            },
        ),
        migrations.CreateModel(
            name='Docenti_gita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=20)),
                ('prezzo', models.FloatField()),
                ('Gita', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.gita')),
            ],
            options={
                'verbose_name_plural': 'Docenti_gita',
            },
        ),
        migrations.CreateModel(
            name='Classe_gita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classe', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.classe')),
                ('Gita', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.gita')),
            ],
            options={
                'verbose_name_plural': 'Classe_gita',
            },
        ),
        migrations.CreateModel(
            name='Presenti_prenotati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gita', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.gita')),
            ],
            options={
                'verbose_name_plural': 'Presenti_prenotati',
            },
        ),
        migrations.AddField(
            model_name='gita',
            name='Proposta_Gita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.proposta_gita'),
        ),
        migrations.CreateModel(
            name='Attività',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titolo', models.CharField(max_length=20)),
                ('Descrizione', models.CharField(max_length=300)),
                ('Costo', models.FloatField()),
                ('Stato', models.CharField(choices=[('IN_ELABORAZIONE', 'In elaborazione'), ('CONFERMATA', 'Confermata'), ('RIFIUTATA', 'Rifiutata')], default='IN_ELABORAZIONE', max_length=20)),
                ('Proposta_Gita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.proposta_gita')),
            ],
            options={
                'verbose_name_plural': 'Attività',
            },
        ),
    ]
