# Generated by Django 5.0.3 on 2024-03-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Underage_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='')),
                ('nome', models.CharField(max_length=20)),
                ('prezzo', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Alunno',
            new_name='Adult_Student',
        ),
        migrations.RenameModel(
            old_name='Prof',
            new_name='Teacher',
        ),
    ]
