# Generated by Django 5.0.3 on 2024-03-22 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_underage_student_rename_alunno_adult_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attività',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=20)),
                ('prezzo', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Attività',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=20)),
                ('prezzo', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Classe',
            },
        ),
        migrations.CreateModel(
            name='Classe_gita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=20)),
                ('prezzo', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Classe_gita',
            },
        ),
        migrations.CreateModel(
            name='Docenti_gita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=20)),
                ('prezzo', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Docenti_gita',
            },
        ),
        migrations.CreateModel(
            name='Documenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=20)),
                ('prezzo', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Documenti',
            },
        ),
        migrations.CreateModel(
            name='Gita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=20)),
                ('Prezzo', models.FloatField()),
                ('Stato', models.CharField(choices=[('IN_PROGRAMMA', 'In programma'), ('IN_CORSO', 'In corso'), ('TERMINATA', 'Terminata')], default='IN_PROGRAMMA', max_length=20)),
                ('Data_partenza', models.DateTimeField(blank=True, null=True)),
                ('Data_ritorno', models.DateTimeField(blank=True, null=True)),
                ('Luogo_partenza', models.CharField(max_length=20)),
                ('Luogo_ritorno', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Gita',
            },
        ),
        migrations.CreateModel(
            name='Presenti_prenotati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=20)),
                ('prezzo', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Presenti_prenotati',
            },
        ),
        migrations.CreateModel(
            name='Proposta_Gita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=20)),
                ('Descrizione', models.CharField(default='prova', max_length=20)),
                ('Data_partenza', models.DateTimeField(blank=True, null=True)),
                ('Luogo', models.CharField(max_length=20)),
                ('Prezzo', models.FloatField()),
                ('Stato', models.CharField(choices=[('IN_ELABORAZIONE', 'In elaborazione'), ('CONFERMATA', 'Confermata'), ('RIFIUTATA', 'Rifiutata')], default='IN_ELABORAZIONE', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Proposte_Gita',
            },
        ),
        migrations.DeleteModel(
            name='Adult_Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Underage_Student',
        ),
        migrations.AddField(
            model_name='gita',
            name='Proposta_Gita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.proposta_gita'),
        ),
    ]
