# Generated by Django 5.0.4 on 2024-05-03 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_presenti_prenotati_utente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docenti_gita',
            name='Nome',
        ),
        migrations.RemoveField(
            model_name='docenti_gita',
            name='prezzo',
        ),
        migrations.AddField(
            model_name='docenti_gita',
            name='utente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
