# Generated by Django 5.0.4 on 2024-05-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_docenti_gita_nome_remove_docenti_gita_prezzo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gita',
            name='Titolo',
        ),
    ]
