# Generated by Django 5.0.3 on 2024-03-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_attività_classe_classe_gita_docenti_gita_documenti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta_gita',
            name='Descrizione',
            field=models.CharField(max_length=20),
        ),
    ]
