# Generated by Django 5.0.3 on 2024-03-22 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_proposta_gita_descrizione'),
    ]

    operations = [
        migrations.AddField(
            model_name='attività',
            name='Proposta_Gita',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.proposta_gita'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposta_gita',
            name='Descrizione',
            field=models.CharField(max_length=300),
        ),
    ]
