# Generated by Django 5.0.4 on 2024-05-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_gita_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gita',
            name='Titolo',
            field=models.CharField(choices=[('IN_PROGRAMMA', 'In programma'), ('IN_CORSO', 'In corso'), ('TERMINATA', 'Terminata')], default='', max_length=20),
        ),
    ]
