# Generated by Django 5.0.3 on 2024-03-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_attività_proposta_gita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attività',
            name='Descrizione',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attività',
            name='Stato',
            field=models.CharField(choices=[('IN_ELABORAZIONE', 'In elaborazione'), ('CONFERMATA', 'Confermata'), ('RIFIUTATA', 'Rifiutata')], default='IN_ELABORAZIONE', max_length=20),
        ),
    ]
