# Generated by Django 5.0.4 on 2024-05-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_gita_titolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gita',
            name='Titolo',
            field=models.CharField(default='', max_length=20),
        ),
    ]
