# Generated by Django 5.0.4 on 2024-05-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_gita_titolo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gita',
            name='Titolo',
        ),
    ]
