# Generated by Django 5.0.4 on 2024-05-04 13:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog', '0002_classe_gita_proposta_gita_documenti_docenti_gita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenti',
            name='groups',
            field=models.ManyToManyField(related_name='documenti', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='anno',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='classe',
            name='sezione',
            field=models.CharField(default='', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]*$', 'Only CAPS characters are allowed.')]),
        ),
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titolo', models.CharField(max_length=20)),
                ('Descrizione', models.CharField(default='', max_length=300)),
                ('Classe', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.classe')),
                ('Documenti', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.documenti')),
                ('Gita', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.gita')),
                ('Proposta_Gita', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.proposta_gita')),
                ('groups', models.ManyToManyField(related_name='notifica', to='auth.group')),
            ],
            options={
                'verbose_name_plural': 'Documenti',
            },
        ),
    ]
