# Generated by Django 5.0.4 on 2024-05-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_documenti_groups_alter_classe_anno_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifica',
            options={'verbose_name_plural': 'Notifica'},
        ),
    ]
